
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'Mantle' 
pod 'LBBlurredImage' 
pod 'TSMessages' 
pod 'ReactiveCocoa'
pod 'SDWebImage', '~>3.7'
pod 'RESideMenu', '~> 4.0.7'
pod 'MMDrawerController', '~> 0.5.7'
